//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Host
    {
        public int id { get; set; }
        public Nullable<int> pacient_id { get; set; }
        public Nullable<int> code { get; set; }
        public Nullable<System.DateTime> dateTimeBegin { get; set; }
        public Nullable<System.DateTime> dateTimeEnd { get; set; }
        public string departament { get; set; }
        public string diagnos { get; set; }
        public string goal { get; set; }
    
        public virtual pacient pacient { get; set; }
    }
}
