//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class med_card
    {
        public int id { get; set; }
        public Nullable<int> pacient_id { get; set; }
        public Nullable<int> med_history_id { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<System.DateTime> date_issuance { get; set; }
    
        public virtual med_history med_history { get; set; }
        public virtual pacient pacient { get; set; }
    }
}
