//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class MedEntities : DbContext
    {

        private static MedEntities _context;

        public MedEntities()
            : base("name=MedEntities")
        {
        }

        public static MedEntities GetContext() 
        {
            if (_context == null) 
                _context = new MedEntities();

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<doctor> doctor { get; set; }
        public virtual DbSet<@event> @event { get; set; }
        public virtual DbSet<Host> Host { get; set; }
        public virtual DbSet<insurance_policy> insurance_policy { get; set; }
        public virtual DbSet<med_card> med_card { get; set; }
        public virtual DbSet<med_history> med_history { get; set; }
        public virtual DbSet<pacient> pacient { get; set; }
        public virtual DbSet<pasport> pasport { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
