//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class pacient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pacient()
        {
            this.Host = new HashSet<Host>();
            this.med_card = new HashSet<med_card>();
        }
    
        public int id { get; set; }
        public Nullable<int> pasport_id { get; set; }
        public Nullable<int> insurance_id { get; set; }
        public Nullable<int> phone { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string place_work { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Host> Host { get; set; }
        public virtual insurance_policy insurance_policy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<med_card> med_card { get; set; }
        public virtual pasport pasport { get; set; }
    }
}
